### PR TITLE
Update 03.Rooms-resource.md

### PR DESCRIPTION
**Pull request by SerafimArts**
Fix issue https://github.com/gitterHQ/gitter/issues/1086

### CODE REVIEW

**Comment by MadLittleMods** [comment]
Thanks for the fix :grinning:

**Comment by SerafimArts** [comment]
@MadLittleMods why close PR without merge? o_0

**Comment by SerafimArts** [comment]
lol

**Comment by MadLittleMods** [comment]
@SerafimArts My mistake, thanks for catching it!

**Pull request merged**
